definitions:
  config:
    /hippo:namespaces/search/searchsettings:
      jcr:primaryType: hipposysedit:templatetype
      jcr:mixinTypes: ['editor:editable', 'mix:referenceable']
      /hipposysedit:nodetype:
        jcr:primaryType: hippo:handle
        jcr:mixinTypes: ['mix:referenceable']
        /hipposysedit:nodetype:
          jcr:primaryType: hipposysedit:nodetype
          jcr:mixinTypes: ['mix:referenceable', 'hipposysedit:remodel']
          hipposysedit:node: true
          hipposysedit:supertype: ['hippo:document', 'hippostd:relaxed', 'hippotranslation:translated']
          hipposysedit:uri: http://www.gov.scot/search/1.0
          /searchtype:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: search:searchtype
            hipposysedit:primary: false
            hipposysedit:type: StaticDropdown
            hipposysedit:validators: [optional]
          /timeoutMillis:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: search:timeoutMillis
            hipposysedit:primary: false
            hipposysedit:type: Long
            hipposysedit:validators: [optional]
          /suggestTimeoutMillis:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: search:suggestTimeoutMillis
            hipposysedit:primary: false
            hipposysedit:type: Long
            hipposysedit:validators: [optional]
          /enabled:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: search:enabled
            hipposysedit:primary: false
            hipposysedit:type: Boolean
            hipposysedit:validators: [optional]
          /bloomreachErrorRate:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: search:bloomreachErrorRate
            hipposysedit:primary: false
            hipposysedit:type: Double
            hipposysedit:validators: [optional]
          /funnelbackErrorRate:
            jcr:primaryType: hipposysedit:field
            hipposysedit:mandatory: false
            hipposysedit:multiple: false
            hipposysedit:ordered: false
            hipposysedit:path: search:funnelbackErrorRate
            hipposysedit:primary: false
            hipposysedit:type: Double
            hipposysedit:validators: [optional]
      /hipposysedit:prototypes:
        jcr:primaryType: hipposysedit:prototypeset
        /hipposysedit:prototype:
          jcr:primaryType: search:searchsettings
          hippostd:holder: holder
          hippostd:state: draft
          hippostdpubwf:createdBy: ''
          hippostdpubwf:lastModifiedBy: ''
          jcr:mixinTypes: ['mix:referenceable']
          hippostdpubwf:lastModificationDate: 2022-07-01T16:13:44.917+01:00
          hippostdpubwf:creationDate: 2022-07-01T16:13:44.917+01:00
          search:searchtype: resilient
          search:enabled: true
          search:timeoutMillis: 500
      /editor:templates:
        jcr:primaryType: editor:templateset
        /_default_:
          jcr:primaryType: frontend:plugincluster
          frontend:properties: [mode]
          frontend:references: [wicket.model, model.compareTo, engine, validator.id]
          frontend:services: [wicket.id, validator.id]
          /root:
            jcr:primaryType: frontend:plugin
            item: ${cluster.id}.field
            plugin.class: org.hippoecm.frontend.service.render.ListViewPlugin
          /enabled:
            jcr:primaryType: frontend:plugin
            caption: Enabled
            field: enabled
            hint: Is the search enabled? Can be used to disable the search page entirely
              if we are experiencing an attack or other operational issue.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /searchtype:
            jcr:primaryType: frontend:plugin
            caption: Search type
            field: searchtype
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            hint: ''
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
              orientation: vertical
              selectable.options: bloomreach=Bloomreach,funnelback-dxp=Funnelback DXP,resilient-dxp=Resilient (Funnelback DXP with bloomreach fallback)
          /timeoutMillis:
            jcr:primaryType: frontend:plugin
            caption: Timeout (millis)
            field: timeoutMillis
            hint: When the type of search is 'resilient' then funnelback wil be called
              with this timeout before falling back to use bloomreach.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /suggestTimeoutMillis:
            jcr:primaryType: frontend:plugin
            caption: Suggest timeout (millis)
            field: suggestTimeoutMillis
            hint: When the type of suggestion is 'resilient' then funnelback wil be called
              with this timeout before falling back to use bloomreach.
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /funnelbackErrorRate:
            jcr:primaryType: frontend:plugin
            caption: Funnelback error rate (0 - 1)
            field: funnelbackErrorRate
            hint: Used to simulate funnelback errors for testing
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig
          /bloomreachErrorRate:
            jcr:primaryType: frontend:plugin
            caption: Bloomreach error rate (0 - 1)
            field: bloomreachErrorRate
            hint: Used to simulate funnelback errors for testing
            plugin.class: org.hippoecm.frontend.editor.plugins.field.PropertyFieldPlugin
            wicket.id: ${cluster.id}.field
            /cluster.options:
              jcr:primaryType: frontend:pluginconfig