schedule-publish-all-label=Schedule publish all in folder...
schedule-publish-all-title=Schedule publication
schedule-publish-all-notification=Schedule publication of all documents bellow '{0}' folder. This operation will affect {1} document(s).
schedule-publish-all-text=Publish on:
schedule-depublish-all-label=Schedule take offline all in folder...
schedule-depublish-all-title=Schedule take offline
schedule-depublish-all-notification=Schedule time to take all documents bellow '{0}' folder offline. This operation will affect {1} document(s).
schedule-depublish-all-text=Publication ends on:
cancel-all-label=Cancel all scheduled requests
schedule-all-action=Schedule